# Generated by Django 5.0.6 on 2025-10-12 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_kk', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt_kk', models.CharField(blank=True, default='', max_length=300)),
                ('excerpt_ru', models.CharField(blank=True, default='', max_length=300)),
                ('body_kk', models.TextField()),
                ('body_ru', models.TextField()),
                ('category', models.CharField(choices=[('advice', 'Медициналық кеңестер / Медицинские советы'), ('event', 'Акциялар / Акции'), ('news', 'Жаңалықтар / Новости')], default='news', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BloodCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_kk', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('hours_kk', models.CharField(blank=True, default='', max_length=120)),
                ('hours_ru', models.CharField(blank=True, default='', max_length=120)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='phone, email, whatsapp, telegram...', max_length=30)),
                ('value', models.CharField(max_length=120)),
                ('label_kk', models.CharField(blank=True, default='', max_length=120)),
                ('label_ru', models.CharField(blank=True, default='', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_kk', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('subtitle_kk', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle_ru', models.CharField(blank=True, default='', max_length=300)),
                ('cta_text_kk', models.CharField(default='Тіркелу', max_length=50)),
                ('cta_text_ru', models.CharField(default='Зарегистрироваться', max_length=50)),
                ('cta_url', models.CharField(default='/register', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title_kk', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('href', models.CharField(help_text='Path or URL', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('app_link_android', models.URLField(blank=True)),
                ('app_link_ios', models.URLField(blank=True)),
                ('footer_text_kk', models.TextField(blank=True, default='')),
                ('footer_text_ru', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonusAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0)),
                ('level', models.CharField(default='Basic', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
