# Generated by Django 5.0.6 on 2025-10-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
