# Generated by Django 5.0.6 on 2025-10-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroblock',
            name='created_at',
        ),
        migrations.AddField(
            model_name='heroblock',
            name='cta_text_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='heroblock',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='heroblock',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='cta_text_kk',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='cta_text_ru',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='cta_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
