# Generated by Django 5.0.6 on 2025-10-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_heroblock_created_at_heroblock_cta_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
