# Generated by Django 5.0.6 on 2025-10-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfig_footer_text_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonus_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bonuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'centers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField()),
                ('volume_ml', models.IntegerField(default=450)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('iin', models.CharField(max_length=12, unique=True)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_kk', models.TextField(verbose_name='О нас (Казахский)')),
                ('text_ru', models.TextField(verbose_name='О нас (Русский)')),
                ('text_en', models.TextField(verbose_name='О нас (Английский)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
