# Generated by Django 5.0.6 on 2025-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('medic', 'Медик'), ('admin', 'Админ')], default='user', max_length=20),
        ),
    ]
