# Generated by Django 5.0.6 on 2025-12-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDonation',
            fields=[
                ('admin_donation_id', models.AutoField(db_column='admin_donation_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='user_id', db_index=True)),
                ('iin', models.CharField(blank=True, db_column='iin', max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, db_column='blood_group', max_length=10, null=True)),
                ('center_id', models.IntegerField(blank=True, db_column='center_id', null=True)),
                ('employee_id', models.IntegerField(blank=True, db_column='employee_id', null=True)),
            ],
            options={
                'db_table': 'admin_donations',
                'managed': False,
            },
        ),
    ]
