# Generated by Django 5.0.6 on 2025-12-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_admindonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSession',
            fields=[
                ('session_id', models.AutoField(db_column='session_id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('time_from', models.TimeField(db_column='time_from')),
                ('time_to', models.TimeField(db_column='time_to')),
                ('room', models.CharField(db_column='room', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'donation_sessions',
                'managed': False,
            },
        ),
    ]
