# Generated by Django 5.0.6 on 2025-12-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_donationsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationsession',
            options={},
        ),
    ]
